### PR TITLE
Fixed the end state.

### PR DESCRIPTION
**Pull request by bruskiza**
@smn, @hodgestar ready for review

### CODE REVIEW

**Comment by bruskiza** [comment]
@miltontony review please...

**Comment by miltontony** [comment]
I don't have any context, but :+1: 
This feels like something the tests should have picked up

**Comment by bruskiza** [comment]
@miltontony thanks kindly, i know.

**Comment by smn** [comment]
Yeah, this is because the tests I wrote only check that the correct response is returned, it doesn't verify that the next state exists. The test harness does allow you to verify that so updating the test to do that would be a good thing to do.

**Pull request merged**
