### PR TITLE
Add 'none' as an option to MSIDN_Entry state.

### PR DESCRIPTION
**Pull request by bruskiza**
Added this an option. If the patient doesn't have a cell number, they can enter none and still proceed.

### CODE REVIEW

**Comment by bruskiza** [comment]
@smn, @hodgestar ready for review... it makes the user to skip the MSIDN screen, but still have to actively engage with the interface to make it pass.

**Comment by bruskiza** [comment]
@smn, @hodgestar ready for review... it makes the user to skip the MSIDN screen, but still have to actively engage with the interface to make it pass.

**Comment by bruskiza** [comment]
@smn, @hodgestar ready for review... it makes the user to skip the MSIDN screen, but still have to actively engage with the interface to make it pass.

**Comment by smn** [comment]
On a feature phone one would have to change from numeric to alphabetical keyboard for this to work. Perhaps just allow for `0` as an input for `none` and potentially reduce the total session length by a couple of seconds?

**Comment by smn** [comment]
:+1: in general though, we can rework the `none` for something else in a different PR if needed.

**Comment by bruskiza** [comment]
yeah... fighting the "it's too easy" to cut corners... cos if it is to easy, data quality falls through the floor.

**Pull request merged**
