### PR TITLE
fix error in logs

### PR DESCRIPTION
**Pull request by g1039**
@hodgestar Ready for review

### CODE REVIEW

**Comment by hodgestar** [comment]
This looks good. We need a test that shows that unrecognized codes result in the error message being displayed.

**Comment by g1039** [comment]
@hodgestar There's already a test for that.

**Comment by hodgestar** [comment]
Link to the test: https://github.com/praekelt/go-jsbox-malaria24/blob/develop/test/app.test.js#L85-L94

**Comment by hodgestar** [comment]
:+1:

**Pull request merged**
